name: Test

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to test'
        required: false


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: ./
      - run: 'echo "Latest tag: ${{ env.LATEST_TAG }}"'